######################################################
#                 Dynamic Collections                #
######################################################

templates:
  trakt:
    trakt_list_details: <<trakt>>

dynamic_collections:
  #Create collections based on the Trakt lists associated with the authenticated user.
  Trakt List Collections:
    template: trakt
    type: trakt_user_lists
    data: me
