######################################################
#             Hidden TV Show Collections             #
######################################################

templates:
  collection:
    optional:
      - show
    tmdb_show: <<show>>
    minimum_items: 1
    collection_mode: hide
    sort_title: <<collection_name>>

collections:
  :
    template: {name: collection, show:  }
  
