######################################################
#                Network Collections                 #
######################################################

templates:
  network:
    smart_filter:
      sort_by: title.asc
      validate: false
      any:
        network: <<network>>
    sort_title: +<<collection_name>>

collections:
  BBC:
    template: { name: network, network: "BBC, BBC America, BBC Choice, BBC First, BBC Four, BBC HD, BBC iPlayer, BBC One, BBC Two, BBC Three, BBC UKTV, CBBC, Cbeebies" }
    url_poster: https://theposterdb.com/api/assets/204360
  #Channel 4:
    #template: { name: network, network: "Channel 4, E4, More4, 4Seven, Film4" }
    #url_poster: https://theposterdb.com/api/assets/204369
  Channel 5:
    template: { name: network, network: "Channel 5, Channel 5 (UK)" }
    url_poster: https://theposterdb.com/api/assets/204372
  ITV:
    template: { name: network, network: "ITV, ITV2, ITV3, ITV4, ITVBe, CITV" }
    url_poster: https://theposterdb.com/api/assets/204451
  Sky:
    template: { name: network, network: "Sky 1, Sky Arts, Sky Atlantic, Sky Atlantic (UK), Sky Cinema, Sky Crime, Sky Documentaries, Sky Living, Sky Max, Sky Nature, Sky One, Sky Sports, Sky Two, Sky Witness, Sky1" }
    url_poster: https://theposterdb.com/api/assets/204467
  HBO:
    template: { name: network, network: "HBO, HBO Canada, HBO Europe, HBO Max" }
    url_poster: https://theposterdb.com/api/assets/204449
  ABC:
    template: { name: network, network: "ABC, ABC (AU), ABS (US), ABC Comedy, ABC Family, ABC Me, ABC Spark, ABC.com, ABC1, ABC3" }
    url_poster: https://theposterdb.com/api/assets/204356
  Showtime:
    template: { name: network, network: "Showtime" }
    url_poster: https://theposterdb.com/api/assets/204463
  Netflix:
    template: { name: network, network: "Netflix" }
    url_poster: https://theposterdb.com/api/assets/204455
  Hulu:
    template: { name: network, network: "Hulu" }
    url_poster: https://theposterdb.com/api/assets/204450
  NBC:
    template: { name: network, network: "Bravo, CNBC, E!, MSNBC, NBC, Oxgen, Peacock, SyFy" }
    url_poster: https://theposterdb.com/api/assets/204454
  #Starz:
    #template: { name: network, network: "Starz" }
    #url_poster: https://theposterdb.com/api/assets/204468
  Amazon Prime:
    template: { name: network, network: "Amazon, Amazon Prime Video, Prime Video" }
    url_poster: https://theposterdb.com/api/assets/204462
  #YouTube:
    #template: { name: network, network: "YouTube, YouTube Premium" }
    #url_poster:
  FOX:
    template: { name: network, network: "FX, FOX, Fox Action Movies, Fox Business Network, Fox Kids, Fox Premium Series, FOX Sports 1, Fox Sports Networks" }
    url_poster: https://theposterdb.com/api/assets/204447
  Disney+:
    template: { name: network, network: "Disney Channel, Disney Channel (UK), Disney Junior, Disney XD, Disney+, Disney+ Hostar" }
    url_poster: https://theposterdb.com/api/assets/204376
  Apple TV+:
    template: { name: network, network: "Apple Music, Apple TV+" }
    url_poster: https://theposterdb.com/api/assets/204359
  Comedy Central:
    template: { name: network, network: "Comedy Central, Comedy Central (UK)" }
    url_poster: https://theposterdb.com/api/assets/204374
  Adult Swim:
    template: { name: network, network: "Adult Swim" }
    url_poster: https://theposterdb.com/api/assets/204357
  Syfy:
    template: { name: network, network: "Syfy" }
    url_poster: https://theposterdb.com/api/assets/204469
  Paramount+:
    template: { name: network, network: "CBS, CBS All Access, Paramount Network, Paramount+" }
    url_poster: https://theposterdb.com/api/assets/204457
  AMC:
    template: { name: network, network: "AMC" }
    url_poster: https://theposterdb.com/api/assets/204358
  Nickelodeon:
    template: { name: network, network: "Nickelodeon" }
    url_poster: https://theposterdb.com/api/assets/204456
  The WB:
    template: { name: network, network: "The WB" }
    url_poster: https://theposterdb.com/api/assets/204472
  The CW:
    template: { name: network, network: "The CW" }
    url_poster: https://theposterdb.com/api/assets/204375
  PBS:
    template: { name: network, network: "PBS, PBS Kids" }
    url_poster: https://theposterdb.com/api/assets/204458
  Hallmark: 
    template: { name: network, network: "Hallmark Channel, Hallmark Movies Now" }
    url_poster: https://theposterdb.com/api/assets/204448
  Bravo:
    template: { name: network, network: "Bravo" }
    url_poster: https://theposterdb.com/api/assets/204367
  Dave:
    template: { name: network, network: "Dave" }
    url_poster: https://theposterdb.com/api/assets/204473
  Lifetime:
    template: { name: network, network: "Lifetime" }
    url_poster: https://theposterdb.com/api/assets/204452
  MTV:
    template: { name: network, network: "MTV" }
    url_poster: https://theposterdb.com/api/assets/204453
  TLC:
    template: { name: network, network: "TLC" }
    url_poster: https://theposterdb.com/api/assets/204470
  truTV:
    template: { name: network, network: "truTV" }
    url_poster: https://theposterdb.com/api/assets/204471
