######################################################
#                Seasonal Collections                #
######################################################

templates:
  seasonal:
    optional:
      - trakt
      - imdb
    smart_label: 
      sort_by: random
      all:
        label: <<smart_label>>
    builder_level: episode
    trakt_list: <<trakt>>
    imdb_list: https://www.imdb.com/<<imdb>>
    schedule: range(<<schedule>>)
    #collection_order: custom
    summary: A collection of <<season>> themed episodes to celebrate the holiday.
    visible_home: true
    visible_shared: true
    delete_not_scheduled: true
    sort_title: +++<<collection_name>
  
collections: 
  Christmas Episodes:
    template: 
      name: seasonal
      schedule: 11/01-01/01
      season: Christmas
      trakt: 
        - https://trakt.tv/users/uyn5hnpr2wdjwksh/lists/christmas-episodes
        - https://trakt.tv/users/philrivers/lists/christmas-episodes 
        - https://trakt.tv/users/b23ant/lists/christmas-episodes
      #imdb: search/keyword/?keywords=christmas-episode
    plex_search:
      all:
        genre.not:
          - Thriller
          - Horror
          - Crime
          - Reality
        any:    
          episode_title: 
            - Christmas
            - Xmas
            - Grinch
            - Santa
            - Claus
            - Reindeer
            - Mistletoe
            - Jingle
            - Merry
            - Snowman
          show_title:
            - Christmas
            - Xmas
            - Grinch
            - Santa
            - Claus
            - Reindeer
            - Mistletoe
            - Jingle
            - Merry
            - Snowman
