######################################################
#                Seasonal Collections                #
######################################################

templates:
  season:
    sort_title: +++<<collection_name>>
    collection_level: episode
    delete_not_scheduled: true
    visible_home: true
    visible_shared: true 
    
templates:
  seasonal:
    optional:
      - trakt
      - imdb 
      - schedule
    smart_label:
      sort_by: random
      all:
        label: <<smart_label>>
    trakt_list: https://trakt.tv/users/<<trakt>>
    imdb_list: https://www.imdb.com/list/<<imdb>>/
    schedule: range(<<schedule>>)
    summary: A collection of <<collection_name>> to celebrate the holiday.
    visible_library: true
    visible_home: true
    visible_shared: true
    delete_not_scheduled: true
    sort_title: +++<<collection_name>>
  
  Christmas Episodes:
    template: { name: Holidays, num: 1, season: christmas }
    schedule: range(11/24-01/07)
    trakt_list:
      - https://trakt.tv/users/uyn5hnpr2wdjwksh/lists/christmas-episodes
      - https://trakt.tv/users/philrivers/lists/christmas-episodes
      - https://trakt.tv/users/b23ant/lists/christmas-episodes
    imdb_list:
      - https://www.imdb.com/search/keyword/?keywords=christmas-episode
    builder_level: episode
    plex_search:
      all:
        genre.not: Reality, Food, Documentary
        any:    
          episode_title: 
           - Christmas
           - Holiday
    test: false
  ```
