######################################################
#                Seasonal Collections                #
######################################################

templates:
  seasonal:
    optional:
      - trakt
      - imdb
    #smart_label: random
    builder_level: episode
    trakt_list: https://trakt.tv/users/<<trakt>>
    imdb_list: https://www.imdb.com/<<imdb>>
    schedule: range(<<schedule>>)
    summary: A collection of <<season>> themed episodes to celebrate the holiday.
    visible_home: true
    visible_shared: true
    delete_not_scheduled: true
    sort_title: +++<<collection_name>
  
collections: 
  Christmas Episodes:
    template: 
      name: seasonal
      schedule: 11/01-01/01
      season: Christmas
      #trakt:
        #- uyn5hnpr2wdjwksh/lists/christmas-episodes
        #- philrivers/lists/christmas-episodes
        #- b23ant/lists/christmas-episodes
      imdb: search/keyword/?keywords=christmas-episode
    plex_search:
      #all:
        #genre.not: Reality, Food, Documentary
      any:    
        episode_title: 
          - Christmas
          - Holiday
