######################################################
#                Seasonal Collections                #
######################################################

templates:
  seasonal:
    optional:
      - trakt
      - imdb 
      - schedule
    smart_label:
      sort_by: random
      all:
        label: <<smart_label>>
    collection_level: episode
    builder_level: episode
    trakt_list: https://trakt.tv/users/<<trakt>>
    imdb_list: https://www.imdb.com/list/<<imdb_list>>/
    imdb_list: https://www.imdb.com/search/keyword/?keywords=<<imdb_keyword>>
    schedule: range(<<schedule>>)
    title_format: <<collection_name>> Episodes
    summary: A collection of <<collection_name>> themed episodes to celebrate the holiday.
    visible_home: true
    visible_shared: true
    delete_not_scheduled: true
    sort_title: +++<<collection_name>>
  
  Christmas:
    template: 
      name: seasonal
      schedule: 11/01-01/01
      trakt:
        - uyn5hnpr2wdjwksh/lists/christmas-episodes
        - philrivers/lists/christmas-episodes
        - b23ant/lists/christmas-episodes
      imdb_keyword:
        - christmas-episode
    builder_level: episode
    plex_search:
      #all:
        #genre.not: Reality, Food, Documentary
      any:    
        episode_title: 
          - Christmas
          - Holiday
