######################################################
#                   TV Collections                   #
######################################################

templates:
  collection:
    optional:
      - show
      - sort
    tmdb_show: <<show>>
    sort_title: <<sort>>

collections:
  American Horror Story:
    template: {name: collection, show: "1413, 113036" }
    summary:
  
  Back in Time for...:
    trakt_list_details: https://trakt.tv/users/mikenobbs/lists/back-in-time-for?sort=released,desc
    
  Bosch:
    template: {name: collection, show: "60585, 153657" }
    summary:

  Breaking Bad:
    template: {name: collection, show: "1396, 60059, 90746, 158704" }
    summary: 

  Buffyverse:
    template: {name: collection, show: "95, 2426, 65316" }
    summary: The Buffyverse refers to the shared fictional universe in which the television series Buffy the Vampire Slayer and Angel are set. This term, originally coined by fans, has since been used even in the titles of published works, and adopted by Joss Whedon, the creator of the fictional universe.

  Clifford the Big Red Dog:
    template: {name: collection, show: "8379, 208995" }
    summary:
  
  Dexter:
    template: {name: collection, show: "1405, 49530, 131927" }
    summary: Dexter is an American crime drama television series. Set in Miami, the series centers on Dexter Morgan, a forensic technician specializing in bloodstain pattern analysis for the fictional Miami Metro Police Department, who leads a secret parallel life as a vigilante serial killer, hunting down murderers who have not been adequately punished by the justice system due to corruption or legal technicalities. Eight years after the series finale Dexter returned in the limited series Dexter: New Blood.

  Doctor Who:
    template: {name: collection, show: "121, 57243" }
    summary: Doctor Who is a British science-fiction television programme broadcast by the BBC since 1963. The programme depicts the adventures of a Time Lord called the Doctor, an extraterrestrial being who appears to be human. The Doctor explores the universe in a time-travelling space ship called the TARDIS, which appears as a blue British police box.

  Long Way:
    template: {name: collection, show: "" }
    summary:
  
  Marvel Cinematic Universe:
    trakt_list: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
    tvdb_show: 393201
    summary: Marvel’s mightiest heroes from across the galaxy gather in Marvel’s Cinematic Universe. Divided into phases, Phase 3 culminates in our heroes facing off against the Mad Titan, Thanos, in a battle that will decide the fate of the universe. But the story is far from over...

  Planet Earth:
    template: {name: collection, show: "82953, 96323, 16946, 115194, 95171" }
    trakt_list: https://trakt.tv/users/bobnxn/lists/planet-earth-stylee
    summary: Planet Earth is a television and film documentary franchise produced and broadcast by the BBC. The franchise began in 2001 with the success of The Blue Planet, and has spawned several series since.

  Scooby-Doo! Animation:
    trakt_list_details: https://trakt.tv/users/mikenobbs/lists/scooby-doo-animation?sort=released,asc
    tvdb_show: 73817

  Star Trek:
    trakt_list:
    summary:
  
  Star Wars:
    trakt_list: https://trakt.tv/users/hector-arruga/lists/stars-wars

  The Walking Dead:
    template: {name: collection, sort: "Walking Dead" }
    trakt_list: https://trakt.tv/users/acoucalancha/lists/the-walking-dead?sort=released,asc
    summary: The Walking Dead is a zombie apocalypse media franchise based on the comic book series of the same name, created by writer Robert Kirkman and artist Tony Moore.
    
  Tom & Jerry:
    trakt_list_details: 
