######################################################
#                TV Show Collections                 #
######################################################

templates:
  collection:
    optional:
      - show
    plex_search:
      validate: true
      all:
        any:
          title: <<title>>
    sort_title: <<collection_name>>
  hide:
    optional:
      - show
    tmdb_show: <<show>>
    minimum_items: 1
    collection_mode: hide
    sort_title: <<collection_name>>

collections:
  Breaking Bad:
    template: {name: collection, show: "1396, 60059, 90746, 158704"}
    summary: Breaking Bad follows Walter White, a middle-aged chemistry teacher, and his descent into the world of drugs and murder following a terminal cancer diagnosis. The show spawned a sequel movie and prequel show, both containing several key characters from Breaking Bad.
  Buffyverse:
    template: {name: collection, show: "95, 2426, 65316"}
    summary: The Buffyverse refers to the shared fictional universe in which the television series Buffy the Vampire Slayer and Angel are set. This term, originally coined by fans, has since been used even in the titles of published works, and adopted by Joss Whedon, the creator of the fictional universe.
    url_poster: https://theposterdb.com/api/assets/249937
  Marvel Cinematic Universe:
    template: {name: collection, show: "118924, 114695"}
    trakt_list: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
    summary: Marvel’s mightiest heroes from across the galaxy gather in Marvel’s Cinematic Universe. Divided into phases, Phase 3 culminates in our heroes facing off against the Mad Titan, Thanos, in a battle that will decide the fate of the universe. But the story is far from over...
    url_poster: https://theposterdb.com/api/assets/188063
  Scooby-Doo! Animation:
    template: {name: collection, title: "Scooby-Doo!"}
    summary:
    url_poster: https://theposterdb.com/api/assets/161484
  Star Trek:
    template: {name: collection, title: Star Trek}
    summary:
    url_poster: https://theposterdb.com/api/assets/21270
  Star Wars:
    template: {name: collection, title: Star Wars ,show: "4194, 60554, 105971, 114478, 3122, 79093, 101978, 71412, 198109, 92830, 85536, 115036, 83867, 82856, 114461, 114479"}
    summary:
    url_poster: https://theposterdb.com/api/assets/152792
  Tom and Jerry:
    template: {name: collection, title: Tom and Jerry}
    summary:
    url_poster: https://theposterdb.com/api/assets/165722
  The Walking Dead:
    template: {name: collection, show: "1402, 62286, 129035, 94305, 136248, 206586"}
    summary:
    url_poster: https://theposterdb.com/api/assets/176383
