######################################################
#                   Movie Overlays                   #
######################################################

overlays:
  IMDb-Top-250:
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&sort=user_rating
    #horizontal_offset: 0
    horizontal_align: right
    #vertical_offset: 0
    vertical_align: bottom
