######################################################
#                    TV Overlays                     #
######################################################
      
overlays:
  IMDb-Top-100:
    overlay:
      name: IMDb-Top-100
    imdb_list: https://www.imdb.com/search/title/?series=tt0096697&sort=user_rating,desc
    limit: 100
    builder_level: episode
