######################################################
#                  Chart Collections                 #
######################################################

templates:
  collection:
    collection_mode: show_items
    sort_title: +<<collection_name>>

collections:
  IMDb Top 250:
    template: {name: collection}
    imdb_chart: top_movies
    summary: The top 250 best movies of all time based on IMDb user ratings.
    collection_order: custom
    url_poster:
