######################################################
#                  Chart Collections                 #
######################################################

templates:
  collection:
    collection_mode: show
    sort_title: +<<collection_name>>

collections:
  IMDb Top 250:
    template: {name: collection}
    imdb_list: https://www.imdb.com/search/title/?groups=top_250&sort=user_rating
    summary: The top 250 best movies of all time based on IMDb user ratings.
    collection_order: custom
    url_poster:
