######################################################
#                  Chart Collections                 #
######################################################

collections:
  IMDb Top 250:
    imdb_list: https://www.imdb.com/chart/top/
    summary:
    collection_order: custom
    url_poster:
