######################################################
#                  Chart Collections                 #
######################################################

collections:
  IMDb Top 250:
    imdb_list:
    summary:
    url_poster:
