######################################################
#                  Chart Collections                 #
######################################################

templates:
  collection:
    sort_title: +<<collection_name>>

collections:
  IMDb Top 250:
    template: {Collection: collection}
    imdb_list: https://www.imdb.com/chart/top/
    summary: The top 250 best movies of all time based on IMDb user ratings.
    collection_order: custom
    url_poster:
