######################################################
#                 Dynamic Collections                #
######################################################

templates:
  tmdb_collection:
    tmdb_collection_details: <<tmdb_collection>>
    sort_title: <<collection_name>>

dynamic_collections:
  #Create collections based on the TMDb Collections associated with items in the library.
  TMDb Collections:
    template: tmdb_collection
    type: tmdb_collection
    addons: 
      8091:       # Alien
        - 135416  # Prometheus
      466463:     # Descendants
        - 805411  # The Royal Wedding
      86066:      # Despicable Me
        - 544669  # Minions
      9485:       # The Fast and the Furious
        - 688042  # Hobbs & Shaw
      8354:       # Ice Age
        - 387893  # Great Egg-Scapade
        - 79218   # Mammoth Christmas
      328:        # Jurassic Park
        - 630322  # Battle at Big Rock
      14740:      # Madagascar
        - 25472   # Merry Madagascar
        - 161143  # Madly Madagascar
        - 10258   # Penguins Christmas Caper
        - 270946  # Penguins of Madagascar
      1733:       # The Mummy
        - 9334    # The Scorpion King
      627517:     # Oz
        - 13155   # Return to Oz
        - 68728   # Oz the Great and Powerful
      86860:      # Scooby-Doo
        - 633815  # The Mystery Begins
      8650:       # Transformers
        - 424783  # Bumblebee
      748:        # X-Men
        - 453993  # The Wolverine
        - 448150  # Deadpool
    exclude:
      - 100693    # 101 Dalmatians (Animated)                                         
      - 124916    # 101 Dalmatians (Live-Action) 
      - 748401    # Aladdin (Live Action)
      - 86027     # Aladdin
      - 312735    # Annie
      - 422834    # Ant-Man
      - 573693    # Aquaman
      - 87250     # Bambi
      - 785583    # Batman the Long Halloween
      - 153010    # Beauty and the Beast                                                
      - 529892    # Black Panther
      - 131295    # Captain America
      - 623911    # Captain Marvel
      - 87118     # Cars
      - 8819      # Casper                                                                   
      - 55419     # Cinderella                                                              
      - 837007    # Cruella                
      - 618529    # Doctor Strange
      - 178117    # The Emperor's New Groove                                               
      - 531799    # Enchanted  
      - 137697    # Finding Nemo
      - 100970    # The Fox and the Hound
      - 386382    # Frozen
      - 535313    # Godzilla
      - 284433    # Guardians of the Galaxy
      - 978459    # Hercules (Disney)                                                       
      - 97456     # The Hunchback of Notre Dame  
      - 131292    # Iron Man
      - 285564    # Jarhead                                                       
      - 307637    # Jingle All the Way                                                     
      - 97459     # The Jungle Book          
      - 97460     # Lady and the Tramp
      - 97461     # Lilo & Stitch                                                             
      - 94032     # The Lion King                                                               
      - 762512    # The Lion King (Reboot)                                                     
      - 33085     # The Little Mermaid             
      - 531331    # Maleficent
      - 209131    # Man of Steel
      - 527439    # Mary Poppins
      - 2344      # The Matrix
      - 137696    # Monsters, Inc.
      - 87236     # Mulan
      - 55422     # Peter Pan
      - 136214    # Pocahontas                                                                
      - 768140    # Pokémon: Detective Pikachu                                                
      - 53159     # The Santa Clause                                                          
      - 1006443   # Scooby-Doo
      - 869205    # Scooby-Doo WWE
      - 762458    # Scooby-Doo Zombie Island 
      - 912503    # Shang-Chi                                                                 
      - 724848    # Shazam!    
      - 334996    # Son of Batman
      - 531241    # Spider-Man (Avengers)
      - 115575    # Star Trek: Alternate Reality                                          
      - 151       # Star Trek: The Original Series                                               
      - 115570    # Star Trek: The Next Generation                                           
      - 10        # Star Wars                                                                    
      - 531242    # Suicide Squad                                                              
      - 729425    # Team Thor         
      - 792425    # Team Thor
      - 86311     # The Avengers
      - 468222    # The Incredibles
      - 57971     # The Rescuers
      - 131296    # Thor
      - 123694    # Timon and Pumbaa
      - 10194     # Toy Story
      - 109608    # Van Helsing
      - 404825    # Wreck-It Ralph
    remove_prefix: The
    remove_suffix: Collection
    title_override:
      948485: The Batman
      86066: Despicable Me & Minions
      263: The Dark Knight
      9485: Fast & Furious
      87251: The Good Witch
      1733: The Mummy
      86860: Scooby-Doo!
      275402: SpongeBob SquarePants
      627517: The Wizard of Oz
