######################################################
#              Hidden Movie Collections              #
######################################################

templates:
  collection:
    optional:
      - movie
    tmdb_movie: <<movie>>
    minimum_items: 1
    collection_mode: hide
    sort_title: <<collection_name>>

collections:
  "Bob's Burgers":
    template: {name: collection, movie: 504827}
    
  Buffyverse:
    template: {name: collection, movie: 10206}
  
  Clifford the Big Red Dog:
    template: {name: collection, movie: 585245}
  
  Friends:
    template: {name: collection, movie: 691179}
  
  Paw Patrol:
    template: {name: collection, movie: 675445}
    
  The Simpsons:
    template: {name: collection, movie: 35}
