######################################################
#                   Custom Metadata                  #
######################################################

metadata:
  
#-Adjustments-#
#-Studio-# 
  Around the World in 80 Days:
    studio: Walt Disney Pictures
  Arrietty:
    studio: Studio Ghibli
  Brave:
    studio: Pixar
  A Bug's Life:
    studio: Pixar
  Camp Rock:
    studio: Walt Disney Pictures
  Cars:
    studio: Pixar
  Cars 2:
    studio: Pixar
  The Cat Returns:
    studio: Studio Ghibli
  "The Chronicles of Narnia: The Voyage of the Dawn Treader":
    studio: Walt Disney Pictures
  Coco:
    studio: Pixar
  "Descendants: The Royal Wedding":
    studio: Disney Television Animation
  Howl's Moving Castle:
    studio: Studio Ghibli
  The Incredibles:
    studio: Pixar
  The Incredibles 2:
    studio: Pixar
  Inside Out:
    studio: Pixar
  Kiki's Delivery Service:
    studio: Studio Ghibli
  "Laputa: Castle in the Sky":
    studio: Studio Ghibli
  Lightyear:
    studio: Pixar
  Luca:
    studio: Pixar
  Monsters University:
    studio: Pixar
  My Neighbor Totoro:
    studio: Studio Ghibli
  "Nausicaä of the Valley of the Wind":
    studio: Studio Ghibli
  Ocean Waves:
    studio: Studio Ghibli
  Onward:
    studio: Pixar
  "Pirates of the Caribbean: At World's End":
    studio: Walt Disney Pictures
  Ponyo:
    studio: Studio Ghibli
  Princess Mononoke:
    studio: Studio Ghibli
  Ratatouille:
    studio: Pixar
  The Red Turtle:
    studio: Studio Ghibli
  Spirited Away:
    studio: Studio Ghibli
  Soul:
    studio: Pixar
  Toy Story 3:
    studio: Pixar
  Toy Story 4:
    studio: Pixar
  "Toy Story Toons: Partysaurus Rex":
    studio: Pixar
  "Toy Story Toons: Small Fry":
    studio: Pixar
  Turning Red:
    studio: Pixar
  WALL•E:
    studio: Pixar
  When Marnie Was There:
    studio: Studio Ghibli
  Whisper of the Heart:
    studio: Studio Ghibli
  The Wind Rises:
    studio: Studio Ghibli
  Zombies 3:
    studio: Disney+
 
#-Genre-Adjustments-#
  "Chip 'n Dale: Rescue Rangers"
    genre.remove: animation
  Enchanted:
    genre.remove: animation
  The Jungle Book (2016):
    title: The Jungle Book
    year: 2016
    genre.remove: animation
  The Lion King (2019):
    title: The Lion King
    year: 2019
    genre.remove: animation
  Mary Poppins Returns:
    genre.remove: animation
  Song of the South:
    genre.remove: animation

#-Collections-#
#-The Matrix-#
  The Animatrix:
    sort_title: Matrix 0
  The Matrix:
    sort_title: Matrix 1
  The Matrix Reloaded:
    sort_title: Matrix 2
  The Matrix Revolutions:
    sort_title: Matrix 3
  The Matrix Resurrections:
    sort_title: Matrix 4

#-Middle Earth-#
  "The Hobbit: An Unexpected Journey":
    sort_title: Middle Earth 1
  "The Hobbit: The Desolation of Smaug":
    sort_title: Middle Earth 2
  "The Hobbit: The Battle of the Five Armies":
    sort_title: Middle Earth 3
  "The Lord of the Rings: The Fellowship of the Ring":
    sort_title: Middle Earth 4
  "The Lord of the Rings: The Two Towers":
    sort_title: Middle Earth 5
  "The Lord of the Rings: The Return of the King":
    sort_title: Middle Earth 6
    
#-Star Wars-#
  "Star Wars: The Phantom Menace":
    alt_title: "Star Wars: Episode I - The Phantom Menace"
    sort_title: Star Wars 1
  "Star Wars: Attack of the Clones":
    alt_title: "Star Wars: Episode II - Attack of the Clones"
    sort_title: Star Wars 2
  "Star Wars: Revenge of the Sith":
    alt_title: "Star Wars: Episode III - Revenge of the Sith"
    sort_title: Star Wars 3
  "Solo: A Star Wars Story":
    sort_title: Star Wars 3.1
  "Rogue One: A Star Wars Story":
    alt_titlt: Rogue One
    sort_title: Star Wars 3.2
  "Star Wars: A New Hope":
    alt_title: Star Wars
    sort_title: Star Wars 4
  "Star Wars: The Empire Strikes Back":
    alt_title: "Star Wars: Episode V - The Empire Strikes Back"
    sort_title: Star Wars 5
  "Star Wars: Return of the Jedi":
    alt_title: Return of the Jedi
    sort_title: Star Wars 6
  "Star Wars: The Force Awakens":
    alt_title: "Star Wars: Episode VII - The Force Awakens"
    sort_title: Star Wars 7
  "Star Wars: The Last Jedi":
    alt_title: "Star Wars: Episode VIII - The Last Jedi"
    sort_title: Star Wars 8
  "Star Wars: The Rise of Skywalker":
    sort_title: Star Wars 9

#-Wizarding World-#
  Fantastic Beasts and Where to Find Them:
    sort_title: Wizarding World 1
  "Fantastic Beasts: The Crimes of Grindelwald":
    sort_title: Wizarding World 2
  "Fantastic Beasts: The Secrets of Dumbledore":
    sort_title: Wizarding World 3
  #Fantastic Beasts 4:
  #   sort_title: Wizarding World 4
  #Fantastic Beasts 5:
  #   sort_title: Wizarding World 5
  Harry Potter and the Philosopher's Stone:
    sort_title: Wizarding World 6
  Harry Potter and the Chamber of Secrets:
    sort_title: Wizarding World 7
  Harry Potter and the Prisoner of Azkaban:
    sort_title: Wizarding World 8
  Harry Potter and the Goblet of Fire:
    sort_title: Wizarding World 9
  Harry Potter and the Order of the Phoenix:
    sort_title: Wizarding World 10
  Harry Potter and the Half-Blood Prince:
    sort_title: Wizarding World 11
  "Harry Potter and the Deathly Hallows: Part 1":
    sort_title: Wizarding World 12
  "Harry Potter and the Deathly Hallows: Part 2":
    sort_title: Wizarding World 13
