######################################################
#                   Custom Metadata                  #
######################################################

metadata:
  
 #-Adjustments-# 
  Brave:
    studio: Pixar
  "The Chronicles of Narnia: The Voyage of the Dawn Treader":
    studio: Walt Disney Pictures
  "Descendants: The Royal Wedding":
    studio: Disney Television Animation
  The Incredibles 2:
    studio: Pixar
  Onward:
    studio: Pixar
  "Pirates of the Caribbean: At World's End":
    studio: Walt Disney Pictures
  Soul:
    studio: Pixar
  Toy Story 4:
    studio: Pixar
  "Toy Story Toons: Partysaurus Rex":
    studio: Pixar
  Seeing Red:
    studio: Pixar
  Enchanted:
    genre.remove: animation
  The Jungle Book (2016):
    title: The Jungle Book
    year: 2016
    genre.remove: animation
  The Lion King (2019):
    title: The Lion King
    year: 2019
    genre.remove: animation
  Mary Poppins Returns:
    genre.remove: animation
  Song of the South:
    genre.remove: animation

#-Collections-#
#-The Matrix-#
  The Animatrix:
    sort_title: Matrix 0
  The Matrix:
    sort_title: Matrix 1
  The Matrix Reloaded:
    sort_title: Matrix 2
  The Matrix Revolutions:
    sort_title: Matrix 3
  The Matrix Resurrections:
    sort_title: Matrix 4

#-Middle Earth-#
  "The Hobbit: An Unexpected Journey":
    sort_title: Middle Earth 1
  "The Hobbit: The Desolation of Smaug":
    sort_title: Middle Earth 2
  "The Hobbit: The Battle of the Five Armies":
    sort_title: Middle Earth 3
  "The Lord of the Rings: The Fellowship of the Ring":
    sort_title: Middle Earth 4
  "The Lord of the Rings: The Two Towers":
    sort_title: Middle Earth 5
  "The Lord of the Rings: The Return of the King":
    sort_title: Middle Earth 6

#-Wizarding World-#
  Fantastic Beasts and Where to Find Them:
    sort_title: Wizarding World 1
  "Fantastic Beasts: The Crimes of Grindelwald":
    sort_title: Wizarding World 2
  #"Fantastic Beasts: The Secrets of Dumbledore":
  #   sort_title: Wizarding World 3
  #Fantastic Beasts 4:
  #   sort_title: Wizarding World 4
  #Fantastic Beasts 5:
  #   sort_title: Wizarding World 5
  Harry Potter and the Philosopher's Stone:
    sort_title: Wizarding World 6
  Harry Potter and the Chamber of Secrets:
    sort_title: Wizarding World 7
  Harry Potter and the Prisoner of Azkaban:
    sort_title: Wizarding World 8
  Harry Potter and the Goblet of Fire:
    sort_title: Wizarding World 9
  Harry Potter and the Order of the Phoenix:
    sort_title: Wizarding World 10
  Harry Potter and the Half-Blood Prince:
    sort_title: Wizarding World 11
  "Harry Potter and the Deathly Hallows: Part 1":
    sort_title: Wizarding World 12
  "Harry Potter and the Deathly Hallows: Part 2":
    sort_title: Wizarding World 13
