######################################################
#                  Movie Collections                 #
######################################################

templates:
  collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sort_title: <<collection_name>>

  tmdb_collection:
    tmdb_collection_details: <<tmdb_collection>>
    sort_title: <<collection_name>>

dynamic_collections:
  #Create collections based on the TMDb Collections associated with items in the library.
  TMDb Collections:
    template: tmdb_collection
    type: tmdb_collection
    exclude:
      - "Monsters, Inc. Collection"
    remove_suffix: Collection

collections:
  
