######################################################
#                Seasonal Collections                #
######################################################

templates:
  seasonal:
    optional:
      - trakt
      - imdb 
      - schedule
    smart_filter:
      
    trakt_list: https://trakt.tv/users/<<trakt>>
    imdb_list: <<imdb>>
    schedule: range(<<schedule>>)
    summary: A collection of movies to celebrate <<collection_name>>.
    visible_library: true
    visible_home: true
    visible_shared: true

collections:
  Christmas:
    template: {name: seasonal, trakt: plexmetamanager/lists/christmas-extravaganza-non-tv-movie, schedule: 11/01-12/31}
  
