######################################################
#                Seasonal Collections                #
######################################################

templates:
  seasonal:
    optional:
      - trakt
      - imdb 
    smart_label:
      sort_by: title.asc
      all:
        label: <<smart_label>>
    trakt_list: https://trakt.tv/users/<<trakt>>
    imdb_list: https://www.imdb.com/<<imdb>>
    schedule: range(<<schedule>>)
    summary: A collection of <<season>> themed movies, as well as movies that are associated with this time of year.
    visible_library: true
    visible_home: true
    visible_shared: true
    sort_title: +++<<collection_name>>

collections:
  Christmas Movies:
    template: 
      name: seasonal
      season: Christmas
      schedule: 11/01-01/01
      trakt: plexmetamanager/lists/christmas-extravaganza-non-tv-movie
      #imdb: search/keyword/?keywords=christmas
