######################################################
#                 Dynamic Collections                #
######################################################

templates:
  tmdb:
    optional:
      - movie
      - summary
      - sort
      - order
      - mode
      - minimum
    tmdb_collection_details: <<tmdb_collection>>
    tmdb_movie: <<movie>>
    summary: <<summary>>
    sort_title: <<sort>>
    collection_order: <<order>>
    collection_mode: <<mode>>
    minimum_items: <<minimum>>

dynamic_collections:
  TMDb Collections:
    template: tmdb
    type: tmdb_collection
    addons: 
      8091:        # Alien
        - 135416   # Prometheus
      86066:       # Despicable Me
        - 544669   # Minions
      9485:        # The Fast and the Furious
        - 688042   # Hobbs & Shaw
      86860:       # Scooby-Doo
        - 633815   # The Mystery Begins
      115575:      # Star Trek: Alternate Reality                                          
        - 151      # Star Trek: The Original Series                                               
        - 115570   # Star Trek: The Next Generation
      748:         # X-Men
        - 453993   # The Wolverine
        - 448150   # Deadpool
    remove_prefix: The
    remove_suffix: Collection
    title_override:
      125574: The Amazing Spider-Man
      948485: The Batman
      86066: Despicable Me & Minions
      263: The Dark Knight
      9485: Fast & Furious
      87251: The Good Witch
      131635: The Hunger Games
      2344: The Matrix
      1733: The Mummy
      86860: Scooby-Doo!
      275402: SpongeBob SquarePants
      115575: Star Trek
      627517: The Wizard of Oz
    template_variables:
      movie:
        466463:        # Descendants
          - 805411     # The Royal Wedding
        1241:          # Harry Potter
          - 899082     # 20th Anniversary
        8354:          # Ice Age
          - 387893     # Egg-Scapade
          - 79218      # Mammoth Christams
        70068:         # IP Man
          - 658009     # Kung Fu Master
          - 643413     # Four Kings
          - 450001     # Master Z
          - 751391     # Crisis Time
          - 44249      # Legend is Born
          - 182127     # Final Fight
          - 44865      # The Grandmaster
        328:           # Jurassic Park
          - 630322     # Battle at Big Rock
        14740:         # Madagascar
          - 25472      # Merry Madagascar
          - 161143     # Madly Madagascar
          - 10258      # Penguins Christmas Caper
          - 270946     # Penguins of Madagascar
        2344:          # The Matrix
          - 55931      # Animatrix
        1733:          # The Mummy
          - 9334       # Scorpion King
        304:           # Ocean's
          - 402900     # Ocean's Eight
        627517:        # Wizard of Oz
          - 13155      # Return to Oz
          - 68728      # Oz the Great and Powerful
        17255:         # Eesident Evil
          - 460458     # Welcome to Racoon City
        10:            # Star Wars
          - 330459     # Rogue One 
          - 348350     # Solo
        131296:        # Thor
          - 413279     # Team Thor
          - 441829     # Team Thor 2
          - 505945     # Team Daryl
        10194:         # Toy Story
          - 82424      # Small Fry
          - 130925     # Partysaurus Rex
          - 77887      # Hawaiian Vacation
          - 213121     # Terror
          - 256835     # Time Forgot
          - 594530     # Lamp Life
          - 718789     # Lightyear
        8650:          # Transformers
          - 424783     # Bumblebee
      sort:
        125574: Amazing Spider-Man
        86311: Avengers
        948485: Batman
        263: Dark Knight
        87251: Good Witch
        97456: Hunchback of Notre Dame
        131635: Hunger Games
        468222: Incredibles
        94032: Lion King
        2344: Matrix
        1733: Mummy
        57971: Rescuers
        627517: Wizard of Oz
      order:
        2344: alpha     # Matrix
        10: alpha       # Star Wars
      summary:
        115575: Space... the final frontier. Star Trek is an American science fiction media franchise created by Gene Roddenberry, which began with the eponymous 1960s television series.   # Star Trek
      mode:
        #86027: hide     # Aladdin
        #422834: hide    # Ant-Man
        #573693: hide    # Aquaman
        #87250: hide     # Bambi
        #785583: hide    # Batman the Long Halloween
        #153010: hide    # Beauty and the Beast                                                
        #529892: hide    # Black Panther
        #131295: hide    # Captain America
        #623911: hide    # Captain Marvel
        #87118: hide     # Cars
        #618529: hide    # Doctor Strange
        #531799: hide    # Enchanted  
        #137697: hide    # Finding Nemo
        #386382: hide    # Frozen
        #284433: hide    # Guardians of the Galaxy
        #97456: hide     # The Hunchback of Notre Dame  
        #131292: hide    # Iron Man
        #97460: hide     # Lady and the Tramp
        #97461: hide     # Lilo & Stitch                                                             
        #94032: hide     # The Lion King
        #531331: hide    # Maleficent
        #527439: hide    # Mary Poppins
        #137696: hide    # Monsters, Inc.
        #55422: hide     # Peter Pan
        #53159: hide     # The Santa Clause
        #912503: hide    # Shang-Chi                                                                 
        #724848: hide    # Shazam!
        #531241: hide    # Spider-Man (Avengers)                                                                                                          
        #531242: hide    # Suicide Squad 
        #86311: hide     # The Avengers
        #468222: hide    # The Incredibles
        #57971: hide     # The Rescuers
        #131296: hide    # Thor
        #10194: hide     # Toy Story
        #468552: hide    # Wonder Woman
        #404825: hide    # Wreck-It Ralph
      minimum:
        893731: 1       # Paw Patrol
    exclude:
      - 100693    # 101 Dalmatians (Animated)                                         
      - 124916    # 101 Dalmatians (Live-Action) 
      - 748401    # Aladdin (Live Action)
      - 312735    # Annie
      - 8819      # Casper                                                                   
      - 55419     # Cinderella                                                              
      - 837007    # Cruella                 
      - 178117    # The Emperor's New Groove                                               
      - 100970    # The Fox and the Hound
      - 535313    # Godzilla
      - 978459    # Hercules (Disney)                                                       
      - 285564    # Jarhead                                                       
      - 307637    # Jingle All the Way                                                     
      - 97459     # The Jungle Book                                                                          
      - 762512    # The Lion King (Reboot)                                                     
      - 33085     # The Little Mermaid             
      - 209131    # Man of Steel
      - 87236     # Mulan
      - 136214    # Pocahontas                                                                
      - 768140    # Pokémon: Detective Pikachu                                                                                                         
      - 1006443   # Scooby-Doo
      - 869205    # Scooby-Doo WWE
      - 762458    # Scooby-Doo Zombie Island      
      - 334996    # Son of Batman                                                             
      - 729425    # Team Thor          
      - 123694    # Timon and Pumbaa
      - 109608    # Van Helsing
