######################################################
#                Combined Collections                #
######################################################

collections:
  Breaking Bad:
    trakt_list_details: https://trakt.tv/users/mikenobbs/lists/breaking-bad
    url_poster:
  Buffyverse:
    trakt_list_details: https://trakt.tv/users/mikenobbs/lists/buffyverse
    summary: The Buffyverse refers to the shared fictional universe in which the television series Buffy the Vampire Slayer and Angel are set. This term, originally coined by fans, has since been used even in the titles of published works, and adopted by Joss Whedon, the creator of the fictional universe.
    url_poster: https://theposterdb.com/api/assets/249937
  Marvel Cinematic Universe:
    trakt_list: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
    summary: Marvel’s mightiest heroes from across the galaxy gather in Marvel’s Cinematic Universe. Divided into phases, Phase 3 culminates in our heroes facing off against the Mad Titan, Thanos, in a battle that will decide the fate of the universe. But the story is far from over...
    url_poster: https://theposterdb.com/api/assets/188063
  Scooby-Doo Animation:
    trakt_list_details: https://trakt.tv/users/mikenobbs/lists/scooby-doo-animation
    tmdb_show: 205755
    url_poster: https://theposterdb.com/api/assets/161484
  Tom and Jerry:
    trakt_list_details: https://trakt.tv/users/mikenobbs/lists/tom-and-jerry
    url_poster: https://theposterdb.com/api/assets/165722
