templates:
  network:
    smart_filter:
      sort_by: alpha
      validate: false
      any:
        network: <<network>>
    sort_title: +<<collection_name>>
#    schedule: weekly (sunday)

collections:
  BBC:
    template: { name: network, network: "BBC, BBC America, BBC Choice, BBC First, BBC Four, BBC HD, BBC iPlayer, BBC One, BBC Two, BBC Three, BBC UKTV, CBBC, Cbeebies" }
    url_poster: 
  Channel 4:
    template: { name: network, network: "Channel 4, E4, More4, 4Seven, Film4" }
    url_poster: 
  ITV:
    template: { name: network, network: "ITV, ITV2, ITV3, ITV4, ITVBe, CITV" }
    url_poster: 
  Sky Shows:
    template: { name: network, network: "Sky 1, Sky Arts, Sky Atlantic, Sky Atlantic (UK), Sky Cinema, Sky Crime, Sky Documentaries, Sky Living, Sky Max, Sky Nature, Sky One, Sky Sports, Sky Two, Sky Witness, Sky1" }
    url_poster: 
  HBO Shows:
    template: { name: network, network: "HBO, HBO Canada, HBO Europe, HBO Max" }
    url_poster: 
  ABC Shows:
    template: { name: network, network: "ABC, ABC (AU), ABS (US), ABC Comedy, ABC Family, ABC Me, ABC Spark, ABC.com, ABC1, ABC3" }
    url_poster: 
  Showtime:
    template: { name: network, network: "Showtime" }
    url_poster: 
  Netflix:
    template: { name: network, network: "Netflix" }
    url_poster: 
  Hulu:
    template: { name: network, network: "Hulu" }
    url_poster:
  NBC Universal:
    template: { name: network, network: "Bravo, CNBC, E!, MSNBC, NBC, Oxgen, Peacock, SyFy" }
    url_poster:
  Starz:
    template: { name: network, network: "Starz" }
    url_poster:
  Amazon Prime:
    template: { name: network, network: "Amazon, Amazon Prime Video, Prime Video" }
    url_poster: 
  YouTube:
    template: { name: network, network: "YouTube, YouTube Premium" }
    url_poster:
  FOX:
    template: { name: network, network: "FX, FOX, Fox Action Movies, Fox Business Network, Fox Kids, Fox Premium Series, FOX Sports 1, Fox Sports Networks" }
    url_poster:
  Disney+:
    template: { name: network, network: "Disney Channel, Disney Channel (UK), Disney Junior, Disney XD, Disney+, Disney+ Hostar" }
    url_poster: 
  Apple TV+:
    template: { name: network, network: "Apple Music, Apple TV+" }
    url_poster:
  Comedy Central Shows:
    template: { name: network, network: "Comedy Central, Comedy Central (UK)" }
    url_poster: 
  Adult Swim Shows:
    template: { name: network, network: "Adult Swim" }
    url_poster: 
  Syfy:
    template: { name: network, network: "77, 3701" }
    url_poster:
