######################################################
#                Playlist Collections                #
######################################################

templates:
  order:
    cache_builders: <<cache>>
    libraries: <<library>>
    trakt_list: https://trakt.tv/users/<<user>>/lists/<<trakt>>
    collection_order: custom
  top:
    cache_builders: <<cache>>
    libraries: <<library>>
    imdb_list: 
      url: https://www.imdb.com/search/title/?series=<<imdb>>&sort=user_rating,desc
      limit: 100
    collection_order: custom

playlists:
  The Simpsons Top 100 Episodes:
    template: {name: top, cache: 1, library: TV Shows, imdb: tt0096697}
    summary: Top 100 episodes of The Simpsons based on IMDb user rating.
  South Park Top 100 Episodes:
    template: {name: top, cache: 1, library: TV Shows, imdb: tt0121955}
    summary: Top 100 episodes of South Park based on IMDb user rating.
  "Star Wars: The Clone Wars - Chronological Order":
    template: {name: order, cache: 365, library: TV Shows, user: tomfin46, trakt: star-wars-the-clone-wars-chronological-episode-order}
    summary: The entire Clone Wars saga, culminating in the fall of the Jedi, in chronological order.
