######################################################
#                Playlist Collections                #
######################################################

templates:
  playlist:
    default:
      limit: 100
      summary: The top 100 episodes of <<imdb>> based on IMDb user ratings.
    optional:
      - cache
      - library
      - trakt
      - imdb
      - limit
      - user 
    cache_builders: <<cache>>
    libraries: <<library>>
    trakt_list: https://trakt.tv/users/<<user>>/lists/<<trakt>>
    imdb_list: 
    - url: https://www.imdb.com/search/title/?series=<<imdb>>&sort=user_rating,desc
    - limit: <<limit>>
    imdb_id: <<imdb>>

playlists:  
  Buffyverse - Chronological Order:
    template: {name: playlist, cache: 365, library: TV Shows, user: psaul3, trakt: buffyverse-viewing-order}
    summary: The Buffyverse in chronological order.
  
  Marvel Cinematic Universe - Chronological Order:
    template: {name: playlist, cache: 1, library: "Movies, TV Shows", user: donxy, trakt: marvel-cinematic-universe}
    summary: Watch Marvel’s mightiest heroes from across the galaxy gather in Marvel’s Cinematic Universe, in chronological order.

  The Simpsons Top 100 Episodes:
    template: {name: playlist, cache: 1, library: TV Shows, imdb: tt0096697}

  South Park Top 100 Episodes:
    template: {name: playlist, cache: 1, library: TV Shows, imdb: tt0121955}
    
  "Star Wars: The Clone Wars - Chronological Order":
    template: {name: playlist, cache: 365, library: TV Shows, user: tomfin46, trakt: star-wars-the-clone-wars-chronological-episode-order}
    summary: The entire Clone Wars saga, culminating in the fall of the Jedi, in chronological order.
